import './reatomArray.test'
import './reatomEnum.test'
import './reatomLinkedList.test'
import './reatomRecord.test'
import './reatomSet.test'
import './reatomString.test'
import './withComputed.test'
