/**
 * Layer 1 for `menu`: the pure policy a menu decides everything with.
 *
 * A menu is the most context-dependent widget of the family: the same key, the
 * same hover, and the same click mean different things depending on whether the
 * menu hangs off a button, off another menu, or off a menubar — and, for the
 * keys, on which side of its anchor it opened. Ariakit resolves that inside its
 * components, against live elements and `useStoreState` reads; here it is a set
 * of functions over plain data, so the whole matrix is node-testable.
 *
 * Ported from [Ariakit](https://github.com/ariakit/ariakit) (MIT, ©
 * 2025–present Ariakit FZ-LLC):
 * `packages/ariakit-react-components/src/menu/menu-button.tsx`
 * (`getInitialFocus`, `hasActiveItem`, the click and hover policies),
 * `menu-list.tsx` (the hide and menubar key maps), and the `hideOnHoverOutside`
 * callback of `menu.tsx`.
 */

import type { CompositeOrientation } from '../composite/getNextId'
import type {
  PopoverBasePlacement,
  PopoverPlacement,
} from '../popover/popoverPlacement'

/**
 * Where focus lands when a menu opens — Ariakit's `initialFocus` state.
 *
 * `'container'` is the menu element itself, which is what a pointer-opened menu
 * wants: nothing looks selected until the user moves. The two others are what
 * the keyboard asks for, and they are resolved against the rendered items.
 */
export type MenuInitialFocus = 'container' | 'first' | 'last'

/**
 * The placement of a submenu, derived from the orientation of the menu it hangs
 * off.
 *
 * A vertical menu — the usual dropdown — grows its submenus sideways, and a
 * horizontal one grows them downwards. Ariakit keeps the same rule in a
 * `sync(parent, ['orientation'])` listener (`menu-store.ts`).
 *
 * @example
 *   menuSubmenuPlacement('vertical') // 'right-start'
 *   menuSubmenuPlacement('horizontal') // 'bottom-start'
 *   menuSubmenuPlacement('both') // 'bottom-start'
 */
export const menuSubmenuPlacement = (
  parentOrientation: CompositeOrientation,
): PopoverPlacement =>
  parentOrientation === 'vertical' ? 'right-start' : 'bottom-start'

/** The minimal shape of a keyboard event the menu policy reads. */
export interface MenuKeyEvent {
  key: string
  defaultPrevented?: boolean
}

/**
 * Which end of the menu an arrow key press on the menu button opens it at.
 *
 * @remarks
 *   Port of `getInitialFocus` (`menu-button.tsx`). The key has to _agree with the
 *   side the menu is on_: `ArrowDown` opens a menu that drops below (and
 *   `ArrowUp` opens it at its last item), while `ArrowRight` only opens a menu
 *   that appears on the right — otherwise the press belongs to the widget
 *   around the button, usually a menubar moving to the next item.
 * @example
 *   mapMenuButtonKeyIntent({ key: 'ArrowDown' }, 'bottom') // 'first'
 *   mapMenuButtonKeyIntent({ key: 'ArrowUp' }, 'bottom') // 'last'
 *   mapMenuButtonKeyIntent({ key: 'ArrowRight' }, 'right') // 'first'
 *   mapMenuButtonKeyIntent({ key: 'ArrowRight' }, 'bottom') // undefined
 *
 * @param event - The key press.
 * @param side - The side of the menu's current placement.
 * @returns The initial focus the press asks for, or `undefined` when the press
 *   is not for this menu.
 */
export const mapMenuButtonKeyIntent = (
  event: MenuKeyEvent,
  side: PopoverBasePlacement,
): Exclude<MenuInitialFocus, 'container'> | undefined => {
  if (event.defaultPrevented) return undefined
  const vertical = side === 'bottom' || side === 'top'

  if (event.key === 'ArrowDown') return vertical ? 'first' : undefined
  if (event.key === 'ArrowUp') return vertical ? 'last' : undefined
  if (event.key === 'ArrowRight') return side === 'right' ? 'first' : undefined
  if (event.key === 'ArrowLeft') return side === 'left' ? 'first' : undefined
  return undefined
}

/** The state a click on the menu button resolves against. */
export interface MenuButtonClickContext {
  /**
   * `event.detail` — the click count, which is `0` for a click the keyboard
   * generated by pressing Enter or Space on the button.
   */
  detail?: number
  /** Whether the menu is currently open. */
  open: boolean
  /** Whether the button belongs to a parent menu, i.e. opens a submenu. */
  hasParentMenu: boolean
}

/** What a click on the menu button does. */
export interface MenuButtonClickIntent {
  /** Whether the menu opens (a submenu button never closes its menu). */
  show: boolean
  /** Whether the click toggles the menu, i.e. closes an open one. */
  toggle: boolean
  /**
   * Whether focus moves into the menu, or `undefined` to leave the flag
   * untouched — a pointer click on a submenu button must not steal focus from
   * the parent menu.
   */
  autoFocusOnShow: boolean | undefined
  /** Where focus lands, or `undefined` to keep the current policy. */
  initialFocus: MenuInitialFocus | undefined
}

/**
 * What a click on the menu button does.
 *
 * @remarks
 *   Port of `MenuButton`'s `onClick` plus the `toggleOnClick: !hasParentMenu` it
 *   passes to `usePopoverDisclosure`. Two rules are worth spelling out:
 *
 *   - A keyboard click ("Enter" or "Space", which the browser reports as a click
 *       with `detail === 0`) focuses the first item, while a pointer click only
 *       focuses the menu container — the pointer is already where the user is
 *       looking.
 *   - A submenu button cannot close its submenu by being clicked again, because the
 *       click that opened it also moved the pointer onto it; Ariakit calls
 *       `showMenu()` unconditionally there.
 *
 * @example
 *   mapMenuButtonClickIntent({
 *     detail: 1,
 *     open: false,
 *     hasParentMenu: false,
 *   })
 *   // { show: false, toggle: true, autoFocusOnShow: true, initialFocus: 'container' }
 *   mapMenuButtonClickIntent({ detail: 0, open: true, hasParentMenu: false })
 *   // a keyboard click on an open menu still re-arms the focus: initialFocus 'first'
 */
export const mapMenuButtonClickIntent = ({
  detail,
  open,
  hasParentMenu,
}: MenuButtonClickContext): MenuButtonClickIntent => {
  const keyboard = !detail
  // Ariakit: "if the menu is hidden or if it's a keyboard click".
  const arming = !open || keyboard

  return {
    show: hasParentMenu,
    toggle: !hasParentMenu,
    autoFocusOnShow: arming && (!hasParentMenu || keyboard) ? true : undefined,
    initialFocus: arming ? (keyboard ? 'first' : 'container') : undefined,
  }
}

/** What an arrow key press inside the menu element does. */
export type MenuListIntent =
  /** Closes this menu, handing focus back to the menu button. */
  | { type: 'hide' }
  /** Moves to another item of the menubar this menu belongs to. */
  | { type: 'menubar'; move: 'next' | 'previous' }

/** The state an arrow key press inside the menu element resolves against. */
export interface MenuListKeyContext {
  /** The side of the menu's current placement. */
  side: PopoverBasePlacement
  /** The menu's own orientation. */
  orientation: CompositeOrientation
  /** Whether the menu is a submenu of another menu. */
  hasParentMenu: boolean
  /**
   * The orientation of the menubar the menu belongs to, or `undefined` when it
   * does not belong to one.
   */
  menubarOrientation?: CompositeOrientation
}

/**
 * Which key press inside a menu element leaves the menu.
 *
 * @remarks
 *   Port of `MenuList`'s `onKeyDown`. Both halves of it are "the arrow that
 *   points back where the menu came from":
 *
 *   - A submenu closes on the arrow that points at its parent — `ArrowLeft` for a
 *       menu that opened to the right, `ArrowUp` for one that dropped below.
 *   - A menu in a menubar hands the perpendicular arrows to the bar, so
 *       `ArrowRight` in a horizontal menubar closes this menu and opens the
 *       next one. The move itself is the menubar's; this only says which way.
 *
 *   A menu that is neither a submenu nor part of a menubar never leaves through
 *   an arrow key, and the vertical arrows of a vertical menu always navigate
 *   its items instead.
 * @example
 *   mapMenuListKeyIntent(
 *     { key: 'ArrowLeft' },
 *     {
 *       side: 'right',
 *       orientation: 'vertical',
 *       hasParentMenu: true,
 *     },
 *   ) // { type: 'hide' }
 *
 * @example
 *   mapMenuListKeyIntent(
 *     { key: 'ArrowRight' },
 *     {
 *       side: 'bottom',
 *       orientation: 'vertical',
 *       hasParentMenu: false,
 *       menubarOrientation: 'horizontal',
 *     },
 *   ) // { type: 'menubar', move: 'next' }
 */
export const mapMenuListKeyIntent = (
  event: MenuKeyEvent,
  context: MenuListKeyContext,
): MenuListIntent | undefined => {
  if (event.defaultPrevented) return undefined

  const { side, orientation, hasParentMenu, menubarOrientation } = context
  // Ariakit's `isHorizontal`: anything that is not explicitly vertical, because
  // a menu navigable on both axes still lays its items out in a column.
  const horizontal = orientation !== 'vertical'
  const inMenubar = menubarOrientation !== undefined

  // Ariakit gates the hide map on `hasParentMenu || (parentMenubar &&
  // !isHorizontal)`: a horizontal menu inside a menubar shares the bar's axis,
  // so its own arrows must not close it.
  if (hasParentMenu || (inMenubar && !horizontal)) {
    const closes =
      (event.key === 'ArrowRight' && side === 'left' && !horizontal) ||
      (event.key === 'ArrowLeft' && side === 'right' && !horizontal) ||
      (event.key === 'ArrowUp' && side === 'bottom' && horizontal) ||
      (event.key === 'ArrowDown' && side === 'top' && horizontal)
    if (closes) return { type: 'hide' }
  }

  if (!inMenubar) return undefined

  const menubarHorizontal = menubarOrientation !== 'vertical'
  const forward = menubarHorizontal ? 'ArrowRight' : 'ArrowDown'
  const backward = menubarHorizontal ? 'ArrowLeft' : 'ArrowUp'

  if (event.key === forward) return { type: 'menubar', move: 'next' }
  if (event.key === backward) return { type: 'menubar', move: 'previous' }
  return undefined
}

/**
 * Whether any of the elements is an expanded menu button — Ariakit's
 * `hasActiveItem`.
 *
 * @remarks
 *   "Another menu of this menubar is already open" is the condition that turns a
 *   menubar into a hover-driven widget: once one menu is open, moving the
 *   pointer along the bar swaps menus, and before that a hover does nothing.
 *   Ariakit reads it off the DOM (`aria-expanded === 'true'`) because a menubar
 *   store knows nothing about the menus its items open, and so does this port —
 *   the attribute is rendered by `props.button`.
 * @example
 *   hasExpandedMenuItem([fileButton, editButton], fileButton) // true if Edit is open
 *
 * @param elements - The menubar's item elements; nullish entries are skipped.
 * @param exclude - An element to ignore, usually the one being hovered.
 */
export const hasExpandedMenuItem = (
  elements: ReadonlyArray<Element | null | undefined>,
  exclude?: Element | null,
): boolean =>
  elements.some((element) => {
    if (!element || element === exclude) return false
    if (typeof element.getAttribute !== 'function') return false
    return element.getAttribute('aria-expanded') === 'true'
  })

/** The context a hover over the menu button resolves against. */
export interface MenuShowOnHoverContext {
  /** Whether the button opens a submenu of another menu. */
  hasParentMenu: boolean
  /** Whether the button is an item of a menubar, and not of a parent menu. */
  parentIsMenubar: boolean
  /** Whether another menu of that menubar is already expanded. */
  menubarExpanded?: boolean
}

/**
 * Whether hovering the menu button opens the menu.
 *
 * @remarks
 *   Port of the `showOnHover` callback `MenuButton` passes to
 *   `useHovercardAnchor`. A submenu always opens on hover — that is what makes
 *   a nested menu feel native — a menu in a menubar only opens while the bar is
 *   already "active", and a lone dropdown never does.
 * @example
 *   resolveMenuShowOnHover({ hasParentMenu: true, parentIsMenubar: false }) // true
 *   resolveMenuShowOnHover({ hasParentMenu: false, parentIsMenubar: false }) // false
 */
export const resolveMenuShowOnHover = ({
  hasParentMenu,
  parentIsMenubar,
  menubarExpanded = false,
}: MenuShowOnHoverContext): boolean => {
  if (hasParentMenu) return true
  if (!parentIsMenubar) return false
  return menubarExpanded
}

/** The context the hover-out policy resolves against. */
export interface MenuHideOnHoverOutsideContext {
  /** Whether the menu is a submenu of another menu. */
  hasParentMenu: boolean
  /** Whether the menu belongs to a menubar. */
  parentIsMenubar: boolean
  /** Whether a menu button has been adopted as the disclosure element. */
  hasDisclosure?: boolean
  /** Whether focus is inside that menu button. */
  disclosureFocused?: boolean
}

/**
 * Whether the menu closes when the pointer wanders off without heading for it.
 *
 * @remarks
 *   Port of the `hideOnHoverOutside` callback of `menu.tsx`, minus the
 *   `fireEvent(disclosureElement, 'mouseout')` re-dispatch it needs to undo a
 *   `blurOnHoverEnd` that never fired — that is a DOM concern, and this port's
 *   item records blur through the model instead of through a synthetic event.
 *
 *   A submenu is a hover-driven thing and always closes this way. A menu in a
 *   menubar closes unless its own button has focus, because then the user is
 *   keyboard-driving the bar and the pointer's position is irrelevant. A lone
 *   dropdown, which was opened by a click, never closes on hover.
 * @example
 *   resolveMenuHideOnHoverOutside({
 *     hasParentMenu: false,
 *     parentIsMenubar: true,
 *     hasDisclosure: true,
 *     disclosureFocused: true,
 *   }) // false — the keyboard owns the menubar right now
 */
export const resolveMenuHideOnHoverOutside = ({
  hasParentMenu,
  parentIsMenubar,
  hasDisclosure = false,
  disclosureFocused = false,
}: MenuHideOnHoverOutsideContext): boolean => {
  if (hasParentMenu) return true
  if (!parentIsMenubar) return false
  if (!hasDisclosure) return true
  return !disclosureFocused
}

/** The context a click on a menu item resolves against. */
export interface MenuItemClickContext {
  /** Whether the per item `hideOnClick` policy is on. */
  hideOnClick: boolean
  /**
   * Whether the item is itself a disclosure — its `aria-haspopup` is set to
   * anything but `'false'`. Clicking a submenu button opens the submenu, so
   * closing the tree would undo the click.
   */
  hasPopup?: boolean
  /**
   * Whether the click navigates away from the page instead of activating the
   * item: a modifier-click on a link that opens a new tab, or one that
   * downloads it. Ariakit's `isOpeningInNewTab` / `isDownloading`.
   */
  navigating?: boolean
}

/**
 * Whether clicking a menu item closes the whole menu tree.
 *
 * @remarks
 *   Port of `MenuItem`'s `onClick`. The default is to close, because a menu item
 *   is a command; the exceptions are an item that opens something (a submenu, a
 *   dialog) and a link the user asked to open elsewhere, where the menu must
 *   stay put so its other items remain reachable.
 * @example
 *   shouldHideMenuOnItemClick({ hideOnClick: true }) // true
 *   shouldHideMenuOnItemClick({ hideOnClick: true, hasPopup: true }) // false
 */
export const shouldHideMenuOnItemClick = ({
  hideOnClick,
  hasPopup = false,
  navigating = false,
}: MenuItemClickContext): boolean => {
  if (navigating) return false
  if (hasPopup) return false
  return hideOnClick
}

/** The minimal shape of a mouse event the link checks read. */
export interface MenuItemMouseEvent {
  metaKey?: boolean
  ctrlKey?: boolean
  altKey?: boolean
}

/** The element fields the link checks read. */
export interface MenuItemLinkDescriptor {
  /** Lowercased tag name. */
  tagName: string
  /** The `type` property of a `button` or `input`. */
  type?: string
}

/**
 * Whether the click navigates away instead of activating the item.
 *
 * @remarks
 *   Merges Ariakit's `isOpeningInNewTab` and `isDownloading`
 *   (`ariakit-utils/src/events.ts`), which differ only in the modifier they
 *   read. The Apple / non-Apple split of `isOpeningInNewTab` is expressed as
 *   "either modifier": a menu item must not close the menu on a modifier-click
 *   that the browser may turn into a navigation, and guessing the platform
 *   wrong is the worse failure.
 * @example
 *   isMenuItemNavigating({ metaKey: true }, { tagName: 'a' }) // true
 *   isMenuItemNavigating({ altKey: true }, { tagName: 'a' }) // true — download
 *   isMenuItemNavigating({ metaKey: true }, { tagName: 'div' }) // false
 */
export const isMenuItemNavigating = (
  event: MenuItemMouseEvent,
  element: MenuItemLinkDescriptor,
): boolean => {
  if (!event.metaKey && !event.ctrlKey && !event.altKey) return false
  if (element.tagName === 'a') return true
  const submit = element.type === 'submit'
  return (element.tagName === 'button' || element.tagName === 'input') && submit
}
